package com.example.demo.model.enums;

public enum Errors {

    NOT_ENOUGH_USERS("NOT_ENOUGH_USERS"),
    NOT_ENOUGH_INFORMATION("NOT_ENOUGH_INFORMATION"),
    NOT_ENOUGH_SINGLE_CHOICE_QUESTIONS("NOT_ENOUGH_SINGLE_CHOICE_QUESTIONS"),
    NOT_ENOUGH_MULTIPLE_CHOICE_QUESTIONS("NOT_ENOUGH_MULTIPLE_CHOICE_QUESTIONS"),
    INVALID_ARGUMENTS("INVALID_ARGUMENTS"),
    EMAIL_USED("EMAIL_USED"),
    LOBBY_IS_OVER("LOBBY_IS_OVER"),
    NOT_ENOUGH_QUESTIONS("NOT_ENOUGH_QUESTIONS"),
    USER_NOT_IN_GAME("USER_NOT_IN_GAME"),
    USER_ALREADY_ANSWERED("USER_ALREADY_ANSWERED"),
    USER_CANT_CHOOSE_TERRITORY("USER_CANT_CHOOSE_TERRITORY"),
    INVALID_CLASS_CODE("INVALID_CLASS_CODE"),
    ERROR_PROCESSING_FILE("ERROR_PROCESSING_FILE"),
    USER_DOESNT_OWN_PACK("USER_DOESNT_OWN_PACK"),
    USER_ALREADY_HAS_PACK("USER_ALREADY_HAS_PACK"),
    USER_DOESNT_HAVE_ACCESS_TO_QUESTION("USER_DOESNT_HAVE_ACCESS_TO_QUESTION");

    private final String value;

    Errors(String value) {
        this.value = value;
    }

    public String getValue() {
        return this.value;
    }
}
